FROM python:3.11
WORKDIR /usr/src/app

COPY . .

RUN mkdir -p ./data
COPY ./data ./data

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip && pip install -r requirements.txt

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "./src/main.py", "--server.port=8501", "--server.address=0.0.0.0"]